### ISSUE TITLE
Request to join team fury design 

### ISSUE THREAD

**Issue by Dera-O** [hng-teamfury/stage2#5]
Hello all.. I'm Dera. Joined team Fury and will like to be on the design team. Please review my design via the Figma link above. Look forward to working with y'all.

**Comment by Dera-O** [comment]
https://www.figma.com/file/aPjcpYEU6YteiCnr5ssmWV/King-s-Landing-Hotel-Website?node-id=0%3A1

**Comment by Rubylena** [comment]
Why would you create a new issue, when there is one for designers already. Please lets be orderly. Thank you
