### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by mocktarissa** [hng-teamfury/stage2#8]
@Mocktar a website where users can log in and pay to get their homework corrected by other users. I guess it will make people more willing to register on the website.

**Comment by EkeChimdi** [comment]
@mocktarissa I have two ideas. 
1. A website where final year students and supervisors can efficiently interact. The website will include supervisor and student team meetings, an event scheduler, e-meeting, chat box amongst others. I can generate an app flow.
2. A website where developers can share resources and get involved in freelancing roles for heavy projects within Africa. I can come up with app flow this too.
 
My HNG ID is hng-04999. I'm a full stack developer. More focused on backend.

**Comment by adekniyi** [comment]
Is this for back end?
